kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prod
  name: kubectl-pf-role
rules:
- apiGroups: [""]
  resources: [services/proxy, pods/portforward]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: kubectl-pf-role-binding
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: kubectl-pf-role
subjects:
- namespace: prod
  kind: ServiceAccount
  name: kubectl-pf
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: kubectl-pf
 namespace: prod
